package com.herbalcalendar.enums;

public enum ActiveCompoundEnum {
    ALKALOIDY,
    FLAWONOIDY,
    SAPONINY,
    GARBINIKI,
    KUMARYNY,
    OLEJKI_ETERYCZNE,
    SLUZY,
    GLIKOZYDY,
    FITOSTEROLE,
    TERPENOIDY,
    POLIFENOLE,
    ANTOCYJANY,
    CHLOROFIL,
    KAROTENOIDY,
    PEKTYNY,
    KWASY_ORGANICZNE,
    ENZYMY_ROSLINNE,
    LAKTONY,
    LIGNANY,
    TANNINY;
}
