# Konfiguracja bazy danych MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/nazwa_bazy?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=aa11aa11

# Konfiguracja Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Konfiguracja JWT
app.jwtSecret=ZmienToNaSuperDlugieTajneHaslo1234567890!
app.jwtExpirationInMs=3600000

spring.security.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=twojemail@gmail.com
spring.mail.password=twojehaslo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Ustawienie kodowania na UTF-8 dla aplikacji
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true